### PR TITLE
Update symfony deps

### PR DESCRIPTION
**Pull request by EmmanuelVella**
To make the bundle works with symfony >=2.1

### CODE REVIEW

**Comment by EmmanuelVella** [comment]
Could someone have a look to this PR please ?

**Comment by iambrosi** [comment]
Travis didn't complete successfully. Make sure you update the lock file according to the new dependencies.

**Comment by EmmanuelVella** [comment]
Thanks, I just updated the lock file.

**Comment by pborreli** [comment]
any news ? would need this Bundle for recent versions of Symfony :panda_face:

**Comment by EmmanuelVella** [comment]
I'm going to update this PR to include sf 2.3 as well

**Comment by EmmanuelVella** [comment]
Done !

**Comment by EmmanuelVella** [comment]
Thanks !

**Comment by pborreli** [comment]
:sparkling_heart: thanks

**Pull request merged**
